/*
 * Student ID : 1690705270
 * Name       : Punyapat Bouruang
 * Section    : 129B
 * No.        : 39
 * Course     : GI113 Computer Programming (GI)
 */
string bossName = "Kirin";
char rank = 'S';
int level = 7;
int maxHp = 240;
int currentHp = 175;
float attackPower = 42.5f;
double critMultiplier = 1.75;
bool isBoss = true;
Console.WriteLine("===== BOSS STATUS:INITIAL =====");
Console.WriteLine($"Name: {bossName}");
Console.WriteLine($"Rank: {rank}");
Console.WriteLine($"Level: {level}");
Console.WriteLine($"HP: {maxHp}");
Console.WriteLine($"Attack Power: {attackPower}");
Console.WriteLine($"Crit Multiplier: {critMultiplier}");
Console.WriteLine($"Is Boss: {isBoss}");
Console.WriteLine();
int hpPercentage = currentHp * 100 / maxHp;
Console.WriteLine($"HP Percentage: {hpPercentage}%");
Console.WriteLine();
Console.WriteLine("Kirin takes 60 Damage!");
currentHp = currentHp - 60;
Console.WriteLine();
Console.WriteLine("===== BOSS STATUS:AFTER DAMAGE =====");
Console.WriteLine($"HP: {currentHp} / {maxHp}");
hpPercentage = currentHp * 100 / maxHp;
Console.WriteLine($"HP Percentage: {hpPercentage}%");
string Com1 = "Astarion";
char Gen1 = 'M';
int levelCom1 = 7;
int maxHpCom1 = 40;
float attackPowerCom1 = 10.5f;
bool Playable1 = true;
Console.WriteLine();
Console.WriteLine("===== Charactor Sheet =====");
Console.WriteLine($"Name: {Com1}");
Console.WriteLine($"Gender: {Gen1}");
Console.WriteLine($"Level: {levelCom1}");
Console.WriteLine($"Max HP: {maxHpCom1}");
Console.WriteLine($"Attack Power: {attackPowerCom1}");
Console.WriteLine($"Playable: {Playable1}");
string Com2 = "Gale";
char Gen2 = 'M';
int levelCom2 = 8;
int maxHpCom2 = 46;
double attackPowerCom2 = 18.5;
bool Playable2 = true;
Console.WriteLine();
Console.WriteLine("===== Charactor Sheet =====");
Console.WriteLine($"Name: {Com2}");
Console.WriteLine($"Gender: {Gen2}");
Console.WriteLine($"Level: {levelCom2}");
Console.WriteLine($"Max HP: {maxHpCom2}");
Console.WriteLine($"Attack Power: {attackPowerCom2}");
Console.WriteLine($"Playable: {Playable2}");
string Com3 = "Karlach";
char Gen3 = 'W';
int levelCom3 = 7;
int maxHpCom3 = 57;
double attackPowerCom3 = 20.5;
bool Playable3 = true;
Console.WriteLine();
Console.WriteLine("===== Charactor Sheet =====");
Console.WriteLine($"Name: {Com3}");
Console.WriteLine($"Gender: {Gen3}");
Console.WriteLine($"Level: {levelCom3}");
Console.WriteLine($"Max HP: {maxHpCom3}");
Console.WriteLine($"Attack Power: {attackPowerCom3}");
Console.WriteLine($"Playable: {Playable3}");
string Com4 = "Shadowheart";
char Gen4 = 'W';
int levelCom4 = 8;
int maxHpCom4 = 56;
double attackPowerCom4 = 12.5;
bool Playable4 = true;
Console.WriteLine();
Console.WriteLine("===== Charactor Sheet =====");
Console.WriteLine($"Name: {Com4}");
Console.WriteLine($"Gender: {Gen4}");
Console.WriteLine($"Level: {levelCom4}");
Console.WriteLine($"Max HP: {maxHpCom4}");
Console.WriteLine($"Attack Power: {attackPowerCom4}");
Console.WriteLine($"Playable: {Playable4}");
